default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  
  desc "deploy new build for beta crashlytics project"
  lane :beta do
    match(type: "development")
    gym(
      scheme: "SACashaloRN",
      export_method: "development",
      xcargs: "ARCHIVE=YES")
    crashlytics(
      api_token: "170c87df1b26132ef28510f40376dd75cb61f489",
      build_secret: "993c5ab5dbbd48e1f585a02fe66762340c4f8860b2136e177d9a9c6c341de21c",
      groups: "sa-cashalo-tester",
      notes: change_log_since_last_tag
    )
  end
  
  def change_log_since_last_tag
    return changelog_from_git_commits(pretty: '%h %s')
  end
end